CREATE TABLE LEARNING_SUBJECT (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME        VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(1000),
    CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UK_LEARNING_SUBJECT_NAME UNIQUE (NAME)
);

CREATE TABLE LEARNING_SUBJECT_PREREQ (
    SUBJECT_ID NUMBER NOT NULL REFERENCES LEARNING_SUBJECT (ID),
    PREREQ_ID  NUMBER NOT NULL REFERENCES LEARNING_SUBJECT (ID),
    PRIMARY KEY (SUBJECT_ID, PREREQ_ID)
);

CREATE TABLE LEARNING_GOAL (
    ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SUBJECT_ID    NUMBER NOT NULL REFERENCES LEARNING_SUBJECT (ID),
    GOAL_TEXT     VARCHAR2(1000) NOT NULL,
    TARGET_LEVEL  VARCHAR2(20),
    CURRENT_LEVEL VARCHAR2(20),
    DEADLINE      DATE,
    CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE LEARNING_STEP (
    ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    GOAL_ID    NUMBER NOT NULL REFERENCES LEARNING_GOAL (ID),
    SEQ        NUMBER(5) NOT NULL,
    TITLE      VARCHAR2(200) NOT NULL,
    OBJECTIVE  VARCHAR2(2000),
    DIFFICULTY NUMBER(1),
    STATUS     VARCHAR2(30) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UK_LEARNING_STEP_SEQ UNIQUE (GOAL_ID, SEQ)
);

CREATE TABLE LEARNING_ASSESSMENT (
    ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    GOAL_ID    NUMBER NOT NULL REFERENCES LEARNING_GOAL (ID),
    STEP_ID    NUMBER REFERENCES LEARNING_STEP (ID),
    TYPE       VARCHAR2(20) NOT NULL,
    QUESTIONS  JSON NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE LEARNING_ANSWER (
    ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ASSESSMENT_ID NUMBER NOT NULL REFERENCES LEARNING_ASSESSMENT (ID),
    ANSWER_TEXT   CLOB NOT NULL,
    SCORES        JSON,
    CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IX_LEARNING_GOAL_SUBJECT ON LEARNING_GOAL (SUBJECT_ID);
CREATE INDEX IX_LEARNING_ASSESSMENT_GOAL ON LEARNING_ASSESSMENT (GOAL_ID);
CREATE INDEX IX_LEARNING_ASSESSMENT_STEP ON LEARNING_ASSESSMENT (STEP_ID);
CREATE INDEX IX_LEARNING_ANSWER_ASSESSMENT ON LEARNING_ANSWER (ASSESSMENT_ID);
